// GCC Absolute Visual Executor V1 — Entity Visual Specifications
// 1:1 Pixel-Perfect Official Replication for GCC Entities
// STRICT ZERO LOGIC MODIFICATION — UI ONLY

export interface EntityVisualSpec {
  entityId: string;
  entityNameAr: string;
  entityNameEn: string;
  category: 'shipping' | 'government' | 'bank' | 'payment_gateway' | 'postal';
  countryCode: string;
  
  // Theme
  colors: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    surface: string;
    text: string;
    textLight: string;
    textOnPrimary: string;
    border: string;
    inputBg: string;
    inputBorder: string;
    button: string;
    buttonHover: string;
    buttonText: string;
  };
  
  // Typography
  typography: {
    fontFamily: string;
    fontFamilyAr: string;
    headingWeight: string;
    bodyWeight: string;
    fontSizeBase: string;
    fontSizeHeading: string;
  };
  
  // Dimensions (exact pixel specs from official mobile apps)
  dimensions: {
    containerMaxWidth: string;
    borderRadius: string;
    buttonHeight: string;
    inputHeight: string;
    inputPaddingX: string;
    inputFontSize: string;
    cardPadding: string;
    headerHeight: string;
    logoWidth: string;
    logoHeight: string;
  };
  
  // Shadows
  shadows: {
    card: string;
    button: string;
    input: string;
    header: string;
    modal: string;
  };
  
  // Assets
  assets: {
    logo: string;
    heroImage: string;
    background: string;
    icons: string;
    ogImage: string;
  };
  
  // UI Component Config
  uiComponents: {
    headerStyle: 'logo-center' | 'logo-left' | 'logo-with-title';
    buttonStyle: 'rounded' | 'pill' | 'rect';
    inputStyle: 'outlined' | 'filled' | 'flat';
    hasGradient: boolean;
    gradientDirection: 'horizontal' | 'vertical' | 'diagonal';
    footerStyle: 'minimal' | 'with-logos' | 'with-links';
  };
}

// ============================================
// SHIPPING ENTITIES
// ============================================

export const ARAMEX_SPEC: EntityVisualSpec = {
  entityId: 'aramex',
  entityNameAr: 'أرامكس',
  entityNameEn: 'Aramex',
  category: 'shipping',
  countryCode: 'AE',
  colors: {
    primary: '#D71920',
    secondary: '#FFFFFF',
    accent: '#333333',
    background: '#F8F8F8',
    surface: '#FFFFFF',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E5E5E5',
    inputBg: '#FFFFFF',
    inputBorder: '#DDDDDD',
    button: '#D71920',
    buttonHover: '#B8151B',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'Inter, Arial, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '428px',
    borderRadius: '12px',
    buttonHeight: '52px',
    inputHeight: '48px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '64px',
    logoWidth: '140px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 2px 8px rgba(0,0,0,0.1)',
    button: '0 4px 12px rgba(215,25,32,0.3)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.25)',
  },
  assets: {
    logo: './assets/logo-aramex.png',
    heroImage: './assets/hero-logistics-trucks.jpg',
    background: '/assets/entities/aramex/bg_pattern.png',
    icons: '/assets/entities/aramex/icons/',
    ogImage: '/og-aramex.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: false,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const DHL_SPEC: EntityVisualSpec = {
  entityId: 'dhl',
  entityNameAr: 'دي إتش إل',
  entityNameEn: 'DHL',
  category: 'shipping',
  countryCode: 'DE',
  colors: {
    primary: '#FFCC00',
    secondary: '#D40511',
    accent: '#000000',
    background: '#FFFFFF',
    surface: '#FFF9E6',
    text: '#000000',
    textLight: '#555555',
    textOnPrimary: '#000000',
    border: '#FFCC00',
    inputBg: '#FFFFFF',
    inputBorder: '#FFCC00',
    button: '#D40511',
    buttonHover: '#A00410',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'Helvetica, Arial, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '428px',
    borderRadius: '4px',
    buttonHeight: '48px',
    inputHeight: '46px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '20px',
    headerHeight: '56px',
    logoWidth: '120px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 1px 4px rgba(0,0,0,0.08)',
    button: '0 2px 8px rgba(212,5,17,0.25)',
    input: '0 1px 2px rgba(0,0,0,0.05)',
    header: '0 1px 3px rgba(0,0,0,0.05)',
    modal: '0 15px 30px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: './assets/logo-dhl.png',
    heroImage: './assets/hero-logistics-trucks.jpg',
    background: '/assets/entities/dhl/bg_pattern.png',
    icons: '/assets/entities/dhl/icons/',
    ogImage: '/og-dhl.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rect',
    inputStyle: 'outlined',
    hasGradient: true,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const FEDEX_SPEC: EntityVisualSpec = {
  entityId: 'fedex',
  entityNameAr: 'فيديكس',
  entityNameEn: 'FedEx',
  category: 'shipping',
  countryCode: 'US',
  colors: {
    primary: '#4D148C',
    secondary: '#FF6600',
    accent: '#FFFFFF',
    background: '#FFFFFF',
    surface: '#F5F0FA',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E0D4ED',
    inputBg: '#FFFFFF',
    inputBorder: '#D0C4DD',
    button: '#4D148C',
    buttonHover: '#3A0F6A',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'Arial, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '428px',
    borderRadius: '8px',
    buttonHeight: '50px',
    inputHeight: '48px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '60px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 2px 6px rgba(0,0,0,0.08)',
    button: '0 4px 10px rgba(77,20,140,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: './assets/logo-fedex.png',
    heroImage: './assets/hero-logistics-trucks.jpg',
    background: '/assets/entities/fedex/bg_pattern.png',
    icons: '/assets/entities/fedex/icons/',
    ogImage: '/og-fedex.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: true,
    gradientDirection: 'diagonal',
    footerStyle: 'with-logos',
  },
};

export const UPS_SPEC: EntityVisualSpec = {
  entityId: 'ups',
  entityNameAr: 'يو بي إس',
  entityNameEn: 'UPS',
  category: 'shipping',
  countryCode: 'US',
  colors: {
    primary: '#351C15',
    secondary: '#FFB500',
    accent: '#FFFFFF',
    background: '#FFFFFF',
    surface: '#FAF8F7',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E5E0DC',
    inputBg: '#FFFFFF',
    inputBorder: '#DDD8D4',
    button: '#351C15',
    buttonHover: '#1F0F0A',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'Arial, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '428px',
    borderRadius: '2px',
    buttonHeight: '48px',
    inputHeight: '46px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '20px',
    headerHeight: '56px',
    logoWidth: '120px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 1px 4px rgba(0,0,0,0.08)',
    button: '0 2px 8px rgba(53,28,21,0.2)',
    input: '0 1px 2px rgba(0,0,0,0.05)',
    header: '0 1px 3px rgba(0,0,0,0.05)',
    modal: '0 15px 30px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/logos/ups-logo.svg',
    heroImage: '/og-ups.jpg',
    background: '/assets/entities/ups/bg_pattern.png',
    icons: '/assets/entities/ups/icons/',
    ogImage: '/og-ups.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rect',
    inputStyle: 'outlined',
    hasGradient: false,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const SMSA_SPEC: EntityVisualSpec = {
  entityId: 'smsa',
  entityNameAr: 'سمسا',
  entityNameEn: 'SMSA Express',
  category: 'shipping',
  countryCode: 'SA',
  colors: {
    primary: '#662D91',
    secondary: '#FF6600',
    accent: '#FFFFFF',
    background: '#FFFFFF',
    surface: '#F7F3FA',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E4D9ED',
    inputBg: '#FFFFFF',
    inputBorder: '#DDD4E5',
    button: '#662D91',
    buttonHover: '#4F2270',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'Arial, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '428px',
    borderRadius: '12px',
    buttonHeight: '52px',
    inputHeight: '48px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '64px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 2px 8px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(102,45,145,0.3)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/smsa-logo.svg',
    heroImage: '/og-smsa.jpg',
    background: '/assets/entities/smsa/bg_pattern.png',
    icons: '/assets/entities/smsa/icons/',
    ogImage: '/og-smsa.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: true,
    gradientDirection: 'diagonal',
    footerStyle: 'with-logos',
  },
};

export const NAQEL_SPEC: EntityVisualSpec = {
  entityId: 'naqel',
  entityNameAr: 'ناقل',
  entityNameEn: 'Naqel Express',
  category: 'shipping',
  countryCode: 'SA',
  colors: {
    primary: '#E61838',
    secondary: '#002E60',
    accent: '#FFFFFF',
    background: '#FFFFFF',
    surface: '#FFF5F7',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#FFD6DD',
    inputBg: '#FFFFFF',
    inputBorder: '#FFCDD5',
    button: '#E61838',
    buttonHover: '#C0132E',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'Arial, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '428px',
    borderRadius: '12px',
    buttonHeight: '52px',
    inputHeight: '48px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '64px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 2px 8px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(230,24,56,0.3)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/og-naqel.jpg',
    heroImage: '/og-naqel.jpg',
    background: '/assets/entities/naqel/bg_pattern.png',
    icons: '/assets/entities/naqel/icons/',
    ogImage: '/og-naqel.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: true,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const ZAJIL_SPEC: EntityVisualSpec = {
  entityId: 'zajil',
  entityNameAr: 'زاجل',
  entityNameEn: 'Zajil Express',
  category: 'shipping',
  countryCode: 'SA',
  colors: {
    primary: '#FFB500',
    secondary: '#003087',
    accent: '#FFFFFF',
    background: '#FFFFFF',
    surface: '#FFF9E6',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#000000',
    border: '#FFE680',
    inputBg: '#FFFFFF',
    inputBorder: '#FFE070',
    button: '#003087',
    buttonHover: '#00235F',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'Arial, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '428px',
    borderRadius: '12px',
    buttonHeight: '52px',
    inputHeight: '48px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '64px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 2px 8px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(0,48,135,0.3)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/og-zajil.jpg',
    heroImage: '/og-zajil.jpg',
    background: '/assets/entities/zajil/bg_pattern.png',
    icons: '/assets/entities/zajil/icons/',
    ogImage: '/og-zajil.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: true,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const SAUDIPOST_SPEC: EntityVisualSpec = {
  entityId: 'saudipost',
  entityNameAr: 'البريد السعودي',
  entityNameEn: 'Saudi Post (SPL)',
  category: 'postal',
  countryCode: 'SA',
  colors: {
    primary: '#006C35',
    secondary: '#FFB81C',
    accent: '#FFFFFF',
    background: '#FFFFFF',
    surface: '#F5FAF7',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#D1E8DC',
    inputBg: '#FFFFFF',
    inputBorder: '#C8E0D4',
    button: '#006C35',
    buttonHover: '#005228',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'Arial, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '428px',
    borderRadius: '14px',
    buttonHeight: '52px',
    inputHeight: '48px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '64px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 2px 8px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(0,108,53,0.3)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/logos/saudipost-logo.png',
    heroImage: '/og-saudipost.jpg',
    background: '/assets/entities/saudipost/bg_pattern.png',
    icons: '/assets/entities/saudipost/icons/',
    ogImage: '/og-saudipost.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: true,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

// ============================================
// GOVERNMENT ENTITIES
// ============================================

export const NAFATH_SPEC: EntityVisualSpec = {
  entityId: 'nafath',
  entityNameAr: 'نفاذ',
  entityNameEn: 'Nafath IAM',
  category: 'government',
  countryCode: 'SA',
  colors: {
    primary: '#006C35',
    secondary: '#FFFFFF',
    accent: '#D32F2F',
    background: '#F5F5F5',
    surface: '#FFFFFF',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E0E0E0',
    inputBg: '#FFFFFF',
    inputBorder: '#DDDDDD',
    button: '#006C35',
    buttonHover: '#005228',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'Taysir, DIN Next Arabic, Cairo, sans-serif',
    fontFamilyAr: 'Taysir, DIN Next Arabic, Cairo, sans-serif',
    headingWeight: '600',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '22px',
  },
  dimensions: {
    containerMaxWidth: '400px',
    borderRadius: '8px',
    buttonHeight: '48px',
    inputHeight: '46px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '20px',
    headerHeight: '56px',
    logoWidth: '120px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 12px rgba(0,0,0,0.05)',
    button: '0 2px 8px rgba(0,108,53,0.2)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 15px 30px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/gov-nafath.png',
    heroImage: '/assets/entities/nafath/security_badge.svg',
    background: '/assets/entities/nafath/gov_bg_light.jpg',
    icons: '/assets/entities/nafath/icons/',
    ogImage: '/og-nafath.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-center',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: false,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const ABSHER_SPEC: EntityVisualSpec = {
  entityId: 'absher',
  entityNameAr: 'أبشر',
  entityNameEn: 'Absher',
  category: 'government',
  countryCode: 'SA',
  colors: {
    primary: '#006C35',
    secondary: '#FFFFFF',
    accent: '#1A5C2E',
    background: '#F5F5F5',
    surface: '#FFFFFF',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E0E0E0',
    inputBg: '#FFFFFF',
    inputBorder: '#DDDDDD',
    button: '#006C35',
    buttonHover: '#005228',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'Taysir, DIN Next Arabic, Cairo, sans-serif',
    fontFamilyAr: 'Taysir, DIN Next Arabic, Cairo, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '414px',
    borderRadius: '8px',
    buttonHeight: '48px',
    inputHeight: '46px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '20px',
    headerHeight: '56px',
    logoWidth: '120px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 12px rgba(0,0,0,0.05)',
    button: '0 2px 8px rgba(0,108,53,0.2)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 15px 30px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/gov-absher.png',
    heroImage: '/assets/entities/absher/hero.jpg',
    background: '/assets/entities/absher/gov_bg.jpg',
    icons: '/assets/entities/absher/icons/',
    ogImage: '/og-absher.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-center',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: false,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const TAWAKKALNA_SPEC: EntityVisualSpec = {
  entityId: 'tawakkalna',
  entityNameAr: 'توكلنا',
  entityNameEn: 'Tawakkalna',
  category: 'government',
  countryCode: 'SA',
  colors: {
    primary: '#006C35',
    secondary: '#00A86B',
    accent: '#FFFFFF',
    background: '#F5F5F5',
    surface: '#FFFFFF',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E0E0E0',
    inputBg: '#FFFFFF',
    inputBorder: '#DDDDDD',
    button: '#006C35',
    buttonHover: '#005228',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'Taysir, DIN Next Arabic, Cairo, sans-serif',
    fontFamilyAr: 'Taysir, DIN Next Arabic, Cairo, sans-serif',
    headingWeight: '600',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '22px',
  },
  dimensions: {
    containerMaxWidth: '414px',
    borderRadius: '12px',
    buttonHeight: '50px',
    inputHeight: '48px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '60px',
    logoWidth: '120px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 12px rgba(0,0,0,0.05)',
    button: '0 2px 8px rgba(0,108,53,0.2)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 15px 30px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/og-tawakkalna.jpg',
    heroImage: '/assets/entities/tawakkalna/hero.jpg',
    background: '/assets/entities/tawakkalna/gov_bg.jpg',
    icons: '/assets/entities/tawakkalna/icons/',
    ogImage: '/og-tawakkalna.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-center',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: false,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const UAE_PASS_SPEC: EntityVisualSpec = {
  entityId: 'uae-pass',
  entityNameAr: 'UAE Pass',
  entityNameEn: 'UAE Pass',
  category: 'government',
  countryCode: 'AE',
  colors: {
    primary: '#CE1126',
    secondary: '#00732F',
    accent: '#000000',
    background: '#FFFFFF',
    surface: '#F5F5F5',
    text: '#000000',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E0E0E0',
    inputBg: '#FFFFFF',
    inputBorder: '#DDDDDD',
    button: '#CE1126',
    buttonHover: '#A00E1E',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'Dubai Font, DIN Next Arabic, Cairo, sans-serif',
    fontFamilyAr: 'Dubai Font, DIN Next Arabic, Cairo, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '428px',
    borderRadius: '4px',
    buttonHeight: '48px',
    inputHeight: '50px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '20px',
    headerHeight: '56px',
    logoWidth: '120px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 2px 4px rgba(0,0,0,0.08)',
    button: '0 2px 8px rgba(206,17,38,0.2)',
    input: '0 1px 2px rgba(0,0,0,0.05)',
    header: '0 1px 3px rgba(0,0,0,0.05)',
    modal: '0 15px 30px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/gov-uae-pass.png',
    heroImage: '/assets/entities/uae-pass/hero.jpg',
    background: '/assets/entities/uae-pass/gov_bg.jpg',
    icons: '/assets/entities/uae-pass/icons/',
    ogImage: '/og-uae-pass.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-center',
    buttonStyle: 'rect',
    inputStyle: 'outlined',
    hasGradient: true,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const DIGITAL_DUBAI_SPEC: EntityVisualSpec = {
  entityId: 'digital-dubai',
  entityNameAr: 'دبي الرقمية',
  entityNameEn: 'Digital Dubai',
  category: 'government',
  countryCode: 'AE',
  colors: {
    primary: '#00A3E0',
    secondary: '#003087',
    accent: '#FFFFFF',
    background: '#F5F9FC',
    surface: '#FFFFFF',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#D4E4F1',
    inputBg: '#FFFFFF',
    inputBorder: '#D0DCE8',
    button: '#00A3E0',
    buttonHover: '#0088C0',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'Dubai Font, DIN Next Arabic, Cairo, sans-serif',
    fontFamilyAr: 'Dubai Font, DIN Next Arabic, Cairo, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '428px',
    borderRadius: '8px',
    buttonHeight: '50px',
    inputHeight: '50px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '60px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 12px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(0,163,224,0.3)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/og-digital-dubai.jpg',
    heroImage: '/assets/entities/digital-dubai/hero.jpg',
    background: '/assets/entities/digital-dubai/gov_bg.jpg',
    icons: '/assets/entities/digital-dubai/icons/',
    ogImage: '/og-digital-dubai.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: true,
    gradientDirection: 'diagonal',
    footerStyle: 'with-logos',
  },
};

export const TAMM_SPEC: EntityVisualSpec = {
  entityId: 'tamm',
  entityNameAr: 'تامم',
  entityNameEn: 'TAMM Abu Dhabi',
  category: 'government',
  countryCode: 'AE',
  colors: {
    primary: '#003087',
    secondary: '#0066CC',
    accent: '#FFFFFF',
    background: '#F5F8FC',
    surface: '#FFFFFF',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#D4E2F1',
    inputBg: '#FFFFFF',
    inputBorder: '#D0DCE8',
    button: '#003087',
    buttonHover: '#00235F',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'Dubai Font, DIN Next Arabic, Cairo, sans-serif',
    fontFamilyAr: 'Dubai Font, DIN Next Arabic, Cairo, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '428px',
    borderRadius: '8px',
    buttonHeight: '50px',
    inputHeight: '50px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '60px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 12px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(0,48,135,0.3)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/og-tamm.jpg',
    heroImage: '/assets/entities/tamm/hero.jpg',
    background: '/assets/entities/tamm/gov_bg.jpg',
    icons: '/assets/entities/tamm/icons/',
    ogImage: '/og-tamm.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: true,
    gradientDirection: 'diagonal',
    footerStyle: 'with-logos',
  },
};

export const SAHEL_SPEC: EntityVisualSpec = {
  entityId: 'sahel',
  entityNameAr: 'سهل',
  entityNameEn: 'Sahel Official',
  category: 'government',
  countryCode: 'KW',
  colors: {
    primary: '#007A33',
    secondary: '#CE1126',
    accent: '#000000',
    background: '#FFFFFF',
    surface: '#F5FAF7',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#D1E8DC',
    inputBg: '#FFFFFF',
    inputBorder: '#C8E0D4',
    button: '#007A33',
    buttonHover: '#005F27',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '600',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '22px',
  },
  dimensions: {
    containerMaxWidth: '426px',
    borderRadius: '10px',
    buttonHeight: '50px',
    inputHeight: '52px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '60px',
    logoWidth: '120px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 8px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(0,122,51,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/gov-sahel.png',
    heroImage: '/assets/entities/sahel/hero.jpg',
    background: '/assets/entities/sahel/gov_bg.jpg',
    icons: '/assets/entities/sahel/icons/',
    ogImage: '/og-sahel.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-center',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: false,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const METRASH2_SPEC: EntityVisualSpec = {
  entityId: 'metrash2',
  entityNameAr: 'متراس2',
  entityNameEn: 'Metrash2',
  category: 'government',
  countryCode: 'QA',
  colors: {
    primary: '#8D1B3D',
    secondary: '#6B1529',
    accent: '#D4AF37',
    background: '#FFFFFF',
    surface: '#F9F9F9',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E0E0E0',
    inputBg: '#FFFFFF',
    inputBorder: '#DDDDDD',
    button: '#8D1B3D',
    buttonHover: '#6B1529',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '600',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '22px',
  },
  dimensions: {
    containerMaxWidth: '430px',
    borderRadius: '6px',
    buttonHeight: '50px',
    inputHeight: '54px',
    inputPaddingX: '18px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '60px',
    logoWidth: '120px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 3px 6px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(141,27,61,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 15px 30px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/gov-metrash2.png',
    heroImage: '/assets/entities/metrash2/hero.jpg',
    background: '/assets/entities/metrash2/gov_bg.jpg',
    icons: '/assets/entities/metrash2/icons/',
    ogImage: '/og-metrash2.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-center',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: false,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const HUKOOMI_SPEC: EntityVisualSpec = {
  entityId: 'hukoomi',
  entityNameAr: 'حكومي',
  entityNameEn: 'Hukoomi Payment Gateway',
  category: 'government',
  countryCode: 'QA',
  colors: {
    primary: '#8D1B3D',
    secondary: '#6B1529',
    accent: '#D4AF37',
    background: '#FFFFFF',
    surface: '#F9F9F9',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E0E0E0',
    inputBg: '#FFFFFF',
    inputBorder: '#DDDDDD',
    button: '#8D1B3D',
    buttonHover: '#6B1529',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '430px',
    borderRadius: '6px',
    buttonHeight: '50px',
    inputHeight: '54px',
    inputPaddingX: '18px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '60px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 3px 6px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(141,27,61,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 15px 30px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/og-hukoomi.jpg',
    heroImage: '/assets/entities/hukoomi/hero.jpg',
    background: '/assets/entities/hukoomi/gov_bg.jpg',
    icons: '/assets/entities/hukoomi/icons/',
    ogImage: '/og-hukoomi.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-center',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: false,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const FAWRI_SPEC: EntityVisualSpec = {
  entityId: 'fawri',
  entityNameAr: 'فوري',
  entityNameEn: 'FAWRI SADAD Bahrain',
  category: 'payment_gateway',
  countryCode: 'BH',
  colors: {
    primary: '#CE1126',
    secondary: '#D32027',
    accent: '#FFFFFF',
    background: '#FFFFFF',
    surface: '#F9F9F9',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E0E0E0',
    inputBg: '#FFFFFF',
    inputBorder: '#DDDDDD',
    button: '#CE1126',
    buttonHover: '#A00E1E',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '600',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '22px',
  },
  dimensions: {
    containerMaxWidth: '414px',
    borderRadius: '8px',
    buttonHeight: '50px',
    inputHeight: '52px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '60px',
    logoWidth: '120px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 8px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(206,17,38,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/og-fawri.jpg',
    heroImage: '/assets/entities/fawri/hero.jpg',
    background: '/assets/entities/fawri/gov_bg.jpg',
    icons: '/assets/entities/fawri/icons/',
    ogImage: '/og-fawri.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-center',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: false,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const OMANNET_SPEC: EntityVisualSpec = {
  entityId: 'omannet',
  entityNameAr: 'عمان نت',
  entityNameEn: 'OmanNet Gov Payment Gateway',
  category: 'payment_gateway',
  countryCode: 'OM',
  colors: {
    primary: '#D0032C',
    secondary: '#009A44',
    accent: '#FFFFFF',
    background: '#FFFFFF',
    surface: '#F8F8F8',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E0E0E0',
    inputBg: '#FFFFFF',
    inputBorder: '#DDDDDD',
    button: '#D0032C',
    buttonHover: '#A80224',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '600',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '22px',
  },
  dimensions: {
    containerMaxWidth: '414px',
    borderRadius: '8px',
    buttonHeight: '50px',
    inputHeight: '52px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '60px',
    logoWidth: '120px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 8px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(208,3,44,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/og-omannet.jpg',
    heroImage: '/assets/entities/omannet/hero.jpg',
    background: '/assets/entities/omannet/gov_bg.jpg',
    icons: '/assets/entities/omannet/icons/',
    ogImage: '/og-omannet.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-center',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: true,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

// ============================================
// PAYMENT GATEWAY ENTITIES
// ============================================

export const SADAD_SPEC: EntityVisualSpec = {
  entityId: 'sadad',
  entityNameAr: 'سداد',
  entityNameEn: 'SADAD Payment System',
  category: 'payment_gateway',
  countryCode: 'SA',
  colors: {
    primary: '#FF6B00',
    secondary: '#54565B',
    accent: '#FFFFFF',
    background: '#F4F4F4',
    surface: '#FFFFFF',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#FFE0C0',
    inputBg: '#FFFFFF',
    inputBorder: '#DDD0C0',
    button: '#FF6B00',
    buttonHover: '#E05E00',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'DIN Next Arabic Medium, Cairo, Tajawal, sans-serif',
    fontFamilyAr: 'DIN Next Arabic Medium, Cairo, Tajawal, sans-serif',
    headingWeight: '700',
    bodyWeight: '500',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '450px',
    borderRadius: '16px',
    buttonHeight: '54px',
    inputHeight: '50px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '64px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 6px 14px rgba(0,0,0,0.08)',
    button: '0 4px 14px rgba(255,107,0,0.3)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/gov-sadad-official.png',
    heroImage: '/assets/entities/sadad/biller_banner.svg',
    background: '/assets/entities/sadad/sadad_bg_orange_light.png',
    icons: '/assets/entities/sadad/icons/',
    ogImage: '/og-sadad.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: true,
    gradientDirection: 'diagonal',
    footerStyle: 'with-logos',
  },
};

export const KNET_SPEC: EntityVisualSpec = {
  entityId: 'knet',
  entityNameAr: 'كي نت',
  entityNameEn: 'KNET',
  category: 'payment_gateway',
  countryCode: 'KW',
  colors: {
    primary: '#007A3D',
    secondary: '#CE1126',
    accent: '#000000',
    background: '#FFFFFF',
    surface: '#F7F7F7',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#DDDDDD',
    inputBg: '#FFFFFF',
    inputBorder: '#DDDDDD',
    button: '#007A3D',
    buttonHover: '#005F2F',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '700',
    bodyWeight: '500',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '426px',
    borderRadius: '14px',
    buttonHeight: '52px',
    inputHeight: '50px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '64px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 10px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(0,122,61,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/gov-knet-logo.png',
    heroImage: '/assets/entities/knet/hero.jpg',
    background: '/assets/entities/knet/bg_pattern.png',
    icons: '/assets/entities/knet/icons/',
    ogImage: '/og-knet.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: true,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const BENEFIT_SPEC: EntityVisualSpec = {
  entityId: 'benefit',
  entityNameAr: 'بنفت',
  entityNameEn: 'BENEFIT',
  category: 'payment_gateway',
  countryCode: 'BH',
  colors: {
    primary: '#CE1126',
    secondary: '#D32027',
    accent: '#FFFFFF',
    background: '#FFFFFF',
    surface: '#F9F9F9',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E0E0E0',
    inputBg: '#FFFFFF',
    inputBorder: '#DDDDDD',
    button: '#CE1126',
    buttonHover: '#A00E1E',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '700',
    bodyWeight: '500',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '414px',
    borderRadius: '14px',
    buttonHeight: '52px',
    inputHeight: '50px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '64px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 10px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(206,17,38,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/gov-benefit-logo.png',
    heroImage: '/assets/entities/benefit/hero.jpg',
    background: '/assets/entities/benefit/bg_pattern.png',
    icons: '/assets/entities/benefit/icons/',
    ogImage: '/og-benefit.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: false,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const DIRHAM_SPEC: EntityVisualSpec = {
  entityId: 'dirham',
  entityNameAr: 'الدرهم الإلكتروني',
  entityNameEn: 'eDirham',
  category: 'payment_gateway',
  countryCode: 'AE',
  colors: {
    primary: '#CE1126',
    secondary: '#00732F',
    accent: '#000000',
    background: '#FFFFFF',
    surface: '#F5F5F5',
    text: '#000000',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E0E0E0',
    inputBg: '#FFFFFF',
    inputBorder: '#DDDDDD',
    button: '#CE1126',
    buttonHover: '#A00E1E',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'Dubai Font, DIN Next Arabic, Cairo, sans-serif',
    fontFamilyAr: 'Dubai Font, DIN Next Arabic, Cairo, sans-serif',
    headingWeight: '700',
    bodyWeight: '500',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '428px',
    borderRadius: '14px',
    buttonHeight: '52px',
    inputHeight: '50px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '64px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 10px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(206,17,38,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/gov-dirham.png',
    heroImage: '/assets/entities/dirham/hero.jpg',
    background: '/assets/entities/dirham/bg_pattern.png',
    icons: '/assets/entities/dirham/icons/',
    ogImage: '/og-dirham.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: true,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const JAYWAN_SPEC: EntityVisualSpec = {
  entityId: 'jaywan',
  entityNameAr: 'جيوان',
  entityNameEn: 'Jaywan',
  category: 'payment_gateway',
  countryCode: 'AE',
  colors: {
    primary: '#CE1126',
    secondary: '#00732F',
    accent: '#000000',
    background: '#FFFFFF',
    surface: '#F5F5F5',
    text: '#000000',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E0E0E0',
    inputBg: '#FFFFFF',
    inputBorder: '#DDDDDD',
    button: '#CE1126',
    buttonHover: '#A00E1E',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'Dubai Font, DIN Next Arabic, Cairo, sans-serif',
    fontFamilyAr: 'Dubai Font, DIN Next Arabic, Cairo, sans-serif',
    headingWeight: '700',
    bodyWeight: '500',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '428px',
    borderRadius: '14px',
    buttonHeight: '52px',
    inputHeight: '50px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '64px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 10px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(206,17,38,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/gov-jaywan.png',
    heroImage: '/assets/entities/jaywan/hero.jpg',
    background: '/assets/entities/jaywan/bg_pattern.png',
    icons: '/assets/entities/jaywan/icons/',
    ogImage: '/og-jaywan.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: true,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const MAAL_SPEC: EntityVisualSpec = {
  entityId: 'maal',
  entityNameAr: 'مال',
  entityNameEn: 'Maal',
  category: 'payment_gateway',
  countryCode: 'OM',
  colors: {
    primary: '#D0032C',
    secondary: '#009A44',
    accent: '#FFFFFF',
    background: '#FFFFFF',
    surface: '#F8F8F8',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E0E0E0',
    inputBg: '#FFFFFF',
    inputBorder: '#DDDDDD',
    button: '#D0032C',
    buttonHover: '#A80224',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '700',
    bodyWeight: '500',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '414px',
    borderRadius: '14px',
    buttonHeight: '52px',
    inputHeight: '50px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '64px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 10px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(208,3,44,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/gov-maal-logo.jpg',
    heroImage: '/assets/entities/maal/hero.jpg',
    background: '/assets/entities/maal/bg_pattern.png',
    icons: '/assets/entities/maal/icons/',
    ogImage: '/og-maal.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: true,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const DUBAIPAY_SPEC: EntityVisualSpec = {
  entityId: 'dubaipay',
  entityNameAr: 'دبي باي',
  entityNameEn: 'Dubai Pay Direct System',
  category: 'payment_gateway',
  countryCode: 'AE',
  colors: {
    primary: '#00A3E0',
    secondary: '#003087',
    accent: '#FFFFFF',
    background: '#F5F9FC',
    surface: '#FFFFFF',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#D4E4F1',
    inputBg: '#FFFFFF',
    inputBorder: '#D0DCE8',
    button: '#00A3E0',
    buttonHover: '#0088C0',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'Dubai Font, DIN Next Arabic, Cairo, sans-serif',
    fontFamilyAr: 'Dubai Font, DIN Next Arabic, Cairo, sans-serif',
    headingWeight: '700',
    bodyWeight: '500',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '428px',
    borderRadius: '16px',
    buttonHeight: '54px',
    inputHeight: '50px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '64px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 6px 14px rgba(0,0,0,0.08)',
    button: '0 4px 14px rgba(0,163,224,0.3)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/og-dubaipay.jpg',
    heroImage: '/assets/entities/dubaipay/hero.jpg',
    background: '/assets/entities/dubaipay/bg_glass.png',
    icons: '/assets/entities/dubaipay/icons/',
    ogImage: '/og-dubaipay.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: true,
    gradientDirection: 'diagonal',
    footerStyle: 'with-logos',
  },
};

export const TASDEED_SPEC: EntityVisualSpec = {
  entityId: 'tasdeed',
  entityNameAr: 'تصديق',
  entityNameEn: 'TAS Tasdeed KNET Gov',
  category: 'government',
  countryCode: 'KW',
  colors: {
    primary: '#003087',
    secondary: '#0066CC',
    accent: '#FFFFFF',
    background: '#F5F8FC',
    surface: '#FFFFFF',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#D4E2F1',
    inputBg: '#FFFFFF',
    inputBorder: '#D0DCE8',
    button: '#003087',
    buttonHover: '#00235F',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '600',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '22px',
  },
  dimensions: {
    containerMaxWidth: '426px',
    borderRadius: '10px',
    buttonHeight: '50px',
    inputHeight: '52px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '60px',
    logoWidth: '120px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 8px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(0,48,135,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/og-tasdeed.jpg',
    heroImage: '/assets/entities/tasdeed/hero.jpg',
    background: '/assets/entities/tasdeed/gov_bg.jpg',
    icons: '/assets/entities/tasdeed/icons/',
    ogImage: '/og-tasdeed.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-center',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: false,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

// ============================================
// BANK ENTITIES (GCC)
// ============================================

export const ALRAJHI_SPEC: EntityVisualSpec = {
  entityId: 'alrajhi',
  entityNameAr: 'مصرف الراجحي',
  entityNameEn: 'Al Rajhi Bank',
  category: 'bank',
  countryCode: 'SA',
  colors: {
    primary: '#006C35',
    secondary: '#FFFFFF',
    accent: '#004D26',
    background: '#F5FAF7',
    surface: '#FFFFFF',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#D1E8DC',
    inputBg: '#FFFFFF',
    inputBorder: '#C8E0D4',
    button: '#006C35',
    buttonHover: '#005228',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '414px',
    borderRadius: '8px',
    buttonHeight: '50px',
    inputHeight: '52px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '60px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 8px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(0,108,53,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: './assets/logo-alrajhibank-com-sa.png',
    heroImage: './assets/hero-bank-riyadh.jpg',
    background: '/assets/entities/alrajhi/bg_pattern.png',
    icons: '/assets/entities/alrajhi/icons/',
    ogImage: '/og-bank-alrajhi.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: false,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const SNB_SPEC: EntityVisualSpec = {
  entityId: 'snb',
  entityNameAr: 'البنك الأهلي السعودي',
  entityNameEn: 'Saudi National Bank',
  category: 'bank',
  countryCode: 'SA',
  colors: {
    primary: '#034638',
    secondary: '#FFFFFF',
    accent: '#006B31',
    background: '#F5FAF7',
    surface: '#FFFFFF',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#D1E8DC',
    inputBg: '#FFFFFF',
    inputBorder: '#C8E0D4',
    button: '#00843D',
    buttonHover: '#006B31',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '414px',
    borderRadius: '8px',
    buttonHeight: '50px',
    inputHeight: '52px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '60px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 8px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(0,132,61,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: './assets/logo-alahli.png',
    heroImage: './assets/hero-bank-riyadh.jpg',
    background: '/assets/entities/snb/bg_pattern.png',
    icons: '/assets/entities/snb/icons/',
    ogImage: '/og-bank-snb.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: false,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const STC_PAY_SPEC: EntityVisualSpec = {
  entityId: 'stc-pay',
  entityNameAr: 'STC Pay',
  entityNameEn: 'STC Pay',
  category: 'bank',
  countryCode: 'SA',
  colors: {
    primary: '#4F2D7F',
    secondary: '#7B4FAF',
    accent: '#FFFFFF',
    background: '#F7F3FA',
    surface: '#FFFFFF',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E4D9ED',
    inputBg: '#FFFFFF',
    inputBorder: '#DDD4E5',
    button: '#4F2D7F',
    buttonHover: '#3D2262',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '414px',
    borderRadius: '12px',
    buttonHeight: '52px',
    inputHeight: '48px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '64px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 8px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(79,45,127,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/og-bank-stc-pay.jpg',
    heroImage: '/assets/entities/stc-pay/hero.jpg',
    background: '/assets/entities/stc-pay/bg_pattern.png',
    icons: '/assets/entities/stc-pay/icons/',
    ogImage: '/og-bank-stc-pay.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: true,
    gradientDirection: 'diagonal',
    footerStyle: 'with-logos',
  },
};

export const MADA_SPEC: EntityVisualSpec = {
  entityId: 'mada',
  entityNameAr: 'مدى',
  entityNameEn: 'mada Gateway',
  category: 'payment_gateway',
  countryCode: 'SA',
  colors: {
    primary: '#004B87',
    secondary: '#00A3E0',
    accent: '#FFFFFF',
    background: '#F5F8FC',
    surface: '#FFFFFF',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#D4E2F1',
    inputBg: '#FFFFFF',
    inputBorder: '#D0DCE8',
    button: '#004B87',
    buttonHover: '#003A6A',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '414px',
    borderRadius: '12px',
    buttonHeight: '52px',
    inputHeight: '48px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '64px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 8px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(0,75,135,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/og-bank-mada.jpg',
    heroImage: '/assets/entities/mada/hero.jpg',
    background: '/assets/entities/mada/bg_pattern.png',
    icons: '/assets/entities/mada/icons/',
    ogImage: '/og-bank-mada.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: true,
    gradientDirection: 'diagonal',
    footerStyle: 'with-logos',
  },
};

export const URPAY_SPEC: EntityVisualSpec = {
  entityId: 'urpay',
  entityNameAr: 'أورباي',
  entityNameEn: 'Urpay',
  category: 'bank',
  countryCode: 'SA',
  colors: {
    primary: '#00A3E0',
    secondary: '#0066CC',
    accent: '#FFFFFF',
    background: '#F5F9FC',
    surface: '#FFFFFF',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#D4E4F1',
    inputBg: '#FFFFFF',
    inputBorder: '#D0DCE8',
    button: '#00A3E0',
    buttonHover: '#0088C0',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '414px',
    borderRadius: '12px',
    buttonHeight: '52px',
    inputHeight: '48px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '64px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 8px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(0,163,224,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/og-urpay.jpg',
    heroImage: '/assets/entities/urpay/hero.jpg',
    background: '/assets/entities/urpay/bg_pattern.png',
    icons: '/assets/entities/urpay/icons/',
    ogImage: '/og-urpay.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: true,
    gradientDirection: 'diagonal',
    footerStyle: 'with-logos',
  },
};

export const ENBD_SPEC: EntityVisualSpec = {
  entityId: 'enbd',
  entityNameAr: 'بنك الإمارات دبي الوطني',
  entityNameEn: 'Emirates NBD',
  category: 'bank',
  countryCode: 'AE',
  colors: {
    primary: '#D50032',
    secondary: '#000000',
    accent: '#FFFFFF',
    background: '#FFFFFF',
    surface: '#F5F5F5',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E0E0E0',
    inputBg: '#FFFFFF',
    inputBorder: '#DDDDDD',
    button: '#D50032',
    buttonHover: '#A80028',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'Dubai Font, DIN Next Arabic, Cairo, sans-serif',
    fontFamilyAr: 'Dubai Font, DIN Next Arabic, Cairo, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '428px',
    borderRadius: '4px',
    buttonHeight: '48px',
    inputHeight: '50px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '20px',
    headerHeight: '56px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 2px 4px rgba(0,0,0,0.08)',
    button: '0 2px 8px rgba(213,0,50,0.2)',
    input: '0 1px 2px rgba(0,0,0,0.05)',
    header: '0 1px 3px rgba(0,0,0,0.05)',
    modal: '0 15px 30px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/bank-logos/emirates-nbd.png',
    heroImage: '/assets/entities/enbd/hero.jpg',
    background: '/assets/entities/enbd/bg_pattern.png',
    icons: '/assets/entities/enbd/icons/',
    ogImage: '/og-bank-enbd.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rect',
    inputStyle: 'outlined',
    hasGradient: false,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const FAB_SPEC: EntityVisualSpec = {
  entityId: 'fab',
  entityNameAr: 'بنك أبوظبي الأول',
  entityNameEn: 'First Abu Dhabi Bank',
  category: 'bank',
  countryCode: 'AE',
  colors: {
    primary: '#000000',
    secondary: '#C8A951',
    accent: '#FFFFFF',
    background: '#FFFFFF',
    surface: '#F5F5F5',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E0E0E0',
    inputBg: '#FFFFFF',
    inputBorder: '#DDDDDD',
    button: '#000000',
    buttonHover: '#333333',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'Dubai Font, DIN Next Arabic, Cairo, sans-serif',
    fontFamilyAr: 'Dubai Font, DIN Next Arabic, Cairo, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '428px',
    borderRadius: '4px',
    buttonHeight: '48px',
    inputHeight: '50px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '20px',
    headerHeight: '56px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 2px 4px rgba(0,0,0,0.08)',
    button: '0 2px 8px rgba(0,0,0,0.2)',
    input: '0 1px 2px rgba(0,0,0,0.05)',
    header: '0 1px 3px rgba(0,0,0,0.05)',
    modal: '0 15px 30px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/bank-logos/fab-uae-new.svg',
    heroImage: '/assets/entities/fab/hero.jpg',
    background: '/assets/entities/fab/bg_pattern.png',
    icons: '/assets/entities/fab/icons/',
    ogImage: '/og-bank-fab.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rect',
    inputStyle: 'outlined',
    hasGradient: false,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const NBK_SPEC: EntityVisualSpec = {
  entityId: 'nbk',
  entityNameAr: 'بنك الكويت الوطني',
  entityNameEn: 'National Bank of Kuwait',
  category: 'bank',
  countryCode: 'KW',
  colors: {
    primary: '#005EB8',
    secondary: '#003D7A',
    accent: '#FFFFFF',
    background: '#F5F8FC',
    surface: '#FFFFFF',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#D4E2F1',
    inputBg: '#FFFFFF',
    inputBorder: '#D0DCE8',
    button: '#005EB8',
    buttonHover: '#004A90',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '426px',
    borderRadius: '10px',
    buttonHeight: '50px',
    inputHeight: '52px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '60px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 8px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(0,94,184,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/bank-logos/nbk-kuwait.png',
    heroImage: '/assets/entities/nbk/hero.jpg',
    background: '/assets/entities/nbk/bg_pattern.png',
    icons: '/assets/entities/nbk/icons/',
    ogImage: '/og-bank-nbk.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: false,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const QNB_SPEC: EntityVisualSpec = {
  entityId: 'qnb',
  entityNameAr: 'بنك قطر الوطني',
  entityNameEn: 'Qatar National Bank',
  category: 'bank',
  countryCode: 'QA',
  colors: {
    primary: '#6E1D3E',
    secondary: '#C8A951',
    accent: '#FFFFFF',
    background: '#FFFFFF',
    surface: '#F9F9F9',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E0E0E0',
    inputBg: '#FFFFFF',
    inputBorder: '#DDDDDD',
    button: '#6E1D3E',
    buttonHover: '#521630',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '430px',
    borderRadius: '6px',
    buttonHeight: '50px',
    inputHeight: '54px',
    inputPaddingX: '18px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '60px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 3px 6px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(110,29,62,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 15px 30px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: './assets/logo-qnb.png',
    heroImage: './assets/hero-bank-dubai.jpg',
    background: '/assets/entities/qnb/bg_pattern.png',
    icons: '/assets/entities/qnb/icons/',
    ogImage: '/og-bank-qnb.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: false,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const BANK_MUSCAT_SPEC: EntityVisualSpec = {
  entityId: 'bank-muscat',
  entityNameAr: 'بنك مسقط',
  entityNameEn: 'Bank Muscat',
  category: 'bank',
  countryCode: 'OM',
  colors: {
    primary: '#E31E24',
    secondary: '#009A44',
    accent: '#FFFFFF',
    background: '#FFFFFF',
    surface: '#F8F8F8',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E0E0E0',
    inputBg: '#FFFFFF',
    inputBorder: '#DDDDDD',
    button: '#E31E24',
    buttonHover: '#B8181D',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '414px',
    borderRadius: '8px',
    buttonHeight: '50px',
    inputHeight: '52px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '60px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 8px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(227,30,36,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/bank-logos/bank-muscat-new.png',
    heroImage: '/assets/entities/bank-muscat/hero.jpg',
    background: '/assets/entities/bank-muscat/bg_pattern.png',
    icons: '/assets/entities/bank-muscat/icons/',
    ogImage: '/og-bank-bank-muscat.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: false,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const NBB_SPEC: EntityVisualSpec = {
  entityId: 'nbb',
  entityNameAr: 'بنك البحرين الوطني',
  entityNameEn: 'National Bank of Bahrain',
  category: 'bank',
  countryCode: 'BH',
  colors: {
    primary: '#E31E24',
    secondary: '#003087',
    accent: '#FFFFFF',
    background: '#FFFFFF',
    surface: '#F9F9F9',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E0E0E0',
    inputBg: '#FFFFFF',
    inputBorder: '#DDDDDD',
    button: '#E31E24',
    buttonHover: '#B8181D',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '414px',
    borderRadius: '8px',
    buttonHeight: '50px',
    inputHeight: '52px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '60px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 8px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(227,30,36,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/bank-logos/nbb-bahrain.jpg',
    heroImage: '/assets/entities/nbb/hero.jpg',
    background: '/assets/entities/nbb/bg_pattern.png',
    icons: '/assets/entities/nbb/icons/',
    ogImage: '/og-bank-nbb.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: false,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

// ============================================
// GOVERNMENT COUNTRY FALLBACK ENTITIES
// ============================================

export const GOV_SA_SPEC: EntityVisualSpec = {
  entityId: 'gov_sa',
  entityNameAr: 'بوابة سداد',
  entityNameEn: 'SADAD Payment Gateway',
  category: 'payment_gateway',
  countryCode: 'SA',
  colors: {
    primary: '#F58220',
    secondary: '#E67317',
    accent: '#FFFFFF',
    background: '#FFF8F2',
    surface: '#FFFFFF',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#FFE5D0',
    inputBg: '#FFFFFF',
    inputBorder: '#FFE0C0',
    button: '#F58220',
    buttonHover: '#E07010',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '450px',
    borderRadius: '16px',
    buttonHeight: '54px',
    inputHeight: '50px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '64px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 6px 14px rgba(0,0,0,0.08)',
    button: '0 4px 14px rgba(245,130,32,0.3)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/gov-sadad-official.png',
    heroImage: '/assets/entities/sadad/biller_banner.svg',
    background: '/assets/entities/sadad/sadad_bg_orange_light.png',
    icons: '/assets/entities/sadad/icons/',
    ogImage: '/og-sadad.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: true,
    gradientDirection: 'diagonal',
    footerStyle: 'with-logos',
  },
};

export const GOV_AE_SPEC: EntityVisualSpec = {
  entityId: 'gov_ae',
  entityNameAr: 'بوابة جيوان',
  entityNameEn: 'Jaywan Payment Gateway',
  category: 'payment_gateway',
  countryCode: 'AE',
  colors: {
    primary: '#CE1126',
    secondary: '#00732F',
    accent: '#000000',
    background: '#FFFFFF',
    surface: '#F5F5F5',
    text: '#000000',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E0E0E0',
    inputBg: '#FFFFFF',
    inputBorder: '#DDDDDD',
    button: '#CE1126',
    buttonHover: '#A00E1E',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'Dubai Font, DIN Next Arabic, Cairo, sans-serif',
    fontFamilyAr: 'Dubai Font, DIN Next Arabic, Cairo, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '428px',
    borderRadius: '14px',
    buttonHeight: '52px',
    inputHeight: '50px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '64px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 10px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(206,17,38,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/gov-uae-logo.jpg',
    heroImage: '/assets/entities/jaywan/hero.jpg',
    background: '/assets/entities/jaywan/bg_pattern.png',
    icons: '/assets/entities/jaywan/icons/',
    ogImage: '/og-jaywan.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: true,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const GOV_KW_SPEC: EntityVisualSpec = {
  entityId: 'gov_kw',
  entityNameAr: 'بوابة كي نت',
  entityNameEn: 'KNET Payment Gateway',
  category: 'payment_gateway',
  countryCode: 'KW',
  colors: {
    primary: '#007A3D',
    secondary: '#CE1126',
    accent: '#000000',
    background: '#FFFFFF',
    surface: '#F7F7F7',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#DDDDDD',
    inputBg: '#FFFFFF',
    inputBorder: '#DDDDDD',
    button: '#007A3D',
    buttonHover: '#005F2F',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '426px',
    borderRadius: '14px',
    buttonHeight: '52px',
    inputHeight: '50px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '64px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 10px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(0,122,61,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/gov-knet-logo.png',
    heroImage: '/assets/entities/knet/hero.jpg',
    background: '/assets/entities/knet/bg_pattern.png',
    icons: '/assets/entities/knet/icons/',
    ogImage: '/og-knet.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: true,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const GOV_QA_SPEC: EntityVisualSpec = {
  entityId: 'gov_qa',
  entityNameAr: 'بوابة حكومي',
  entityNameEn: 'Hukoomi Payment Gateway',
  category: 'payment_gateway',
  countryCode: 'QA',
  colors: {
    primary: '#8D1B3D',
    secondary: '#6B1529',
    accent: '#D4AF37',
    background: '#FFFFFF',
    surface: '#F9F9F9',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E0E0E0',
    inputBg: '#FFFFFF',
    inputBorder: '#DDDDDD',
    button: '#8D1B3D',
    buttonHover: '#6B1529',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '430px',
    borderRadius: '6px',
    buttonHeight: '50px',
    inputHeight: '54px',
    inputPaddingX: '18px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '60px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 3px 6px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(141,27,61,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 15px 30px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/gov-qatar-logo.png',
    heroImage: '/assets/entities/hukoomi/hero.jpg',
    background: '/assets/entities/hukoomi/gov_bg.jpg',
    icons: '/assets/entities/hukoomi/icons/',
    ogImage: '/og-hukoomi.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-center',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: false,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const GOV_BH_SPEC: EntityVisualSpec = {
  entityId: 'gov_bh',
  entityNameAr: 'بوابة فوري',
  entityNameEn: 'FAWRI Payment Gateway',
  category: 'payment_gateway',
  countryCode: 'BH',
  colors: {
    primary: '#CE1126',
    secondary: '#D32027',
    accent: '#FFFFFF',
    background: '#FFFFFF',
    surface: '#F9F9F9',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E0E0E0',
    inputBg: '#FFFFFF',
    inputBorder: '#DDDDDD',
    button: '#CE1126',
    buttonHover: '#A00E1E',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '600',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '22px',
  },
  dimensions: {
    containerMaxWidth: '414px',
    borderRadius: '8px',
    buttonHeight: '50px',
    inputHeight: '52px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '60px',
    logoWidth: '120px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 8px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(206,17,38,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/gov-benefit.png',
    heroImage: '/assets/entities/fawri/hero.jpg',
    background: '/assets/entities/fawri/gov_bg.jpg',
    icons: '/assets/entities/fawri/icons/',
    ogImage: '/og-fawri.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-center',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: false,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

export const GOV_OM_SPEC: EntityVisualSpec = {
  entityId: 'gov_om',
  entityNameAr: 'بوابة مال',
  entityNameEn: 'Maal Payment Gateway',
  category: 'payment_gateway',
  countryCode: 'OM',
  colors: {
    primary: '#D0032C',
    secondary: '#009A44',
    accent: '#FFFFFF',
    background: '#FFFFFF',
    surface: '#F8F8F8',
    text: '#1A1A1A',
    textLight: '#666666',
    textOnPrimary: '#FFFFFF',
    border: '#E0E0E0',
    inputBg: '#FFFFFF',
    inputBorder: '#DDDDDD',
    button: '#D0032C',
    buttonHover: '#A80224',
    buttonText: '#FFFFFF',
  },
  typography: {
    fontFamily: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    fontFamilyAr: 'DIN Next Arabic, Cairo, Tajawal, sans-serif',
    headingWeight: '700',
    bodyWeight: '400',
    fontSizeBase: '16px',
    fontSizeHeading: '24px',
  },
  dimensions: {
    containerMaxWidth: '414px',
    borderRadius: '14px',
    buttonHeight: '52px',
    inputHeight: '50px',
    inputPaddingX: '16px',
    inputFontSize: '16px',
    cardPadding: '24px',
    headerHeight: '64px',
    logoWidth: '130px',
    logoHeight: 'auto',
  },
  shadows: {
    card: '0 4px 10px rgba(0,0,0,0.08)',
    button: '0 4px 12px rgba(208,3,44,0.25)',
    input: '0 1px 3px rgba(0,0,0,0.05)',
    header: '0 2px 4px rgba(0,0,0,0.05)',
    modal: '0 20px 40px rgba(0,0,0,0.2)',
  },
  assets: {
    logo: '/gov-maal-logo.jpg',
    heroImage: '/assets/entities/maal/hero.jpg',
    background: '/assets/entities/maal/bg_pattern.png',
    icons: '/assets/entities/maal/icons/',
    ogImage: '/og-maal.jpg',
  },
  uiComponents: {
    headerStyle: 'logo-with-title',
    buttonStyle: 'rounded',
    inputStyle: 'outlined',
    hasGradient: true,
    gradientDirection: 'horizontal',
    footerStyle: 'with-logos',
  },
};

// ============================================
// ENTITY REGISTRY MAP
// ============================================

export const ENTITY_VISUAL_REGISTRY: Record<string, EntityVisualSpec> = {
  // Shipping
  aramex: ARAMEX_SPEC,
  dhl: DHL_SPEC,
  fedex: FEDEX_SPEC,
  ups: UPS_SPEC,
  smsa: SMSA_SPEC,
  naqel: NAQEL_SPEC,
  zajil: ZAJIL_SPEC,
  saudipost: SAUDIPOST_SPEC,

  // Government
  nafath: NAFATH_SPEC,
  absher: ABSHER_SPEC,
  tawakkalna: TAWAKKALNA_SPEC,
  'uae-pass': UAE_PASS_SPEC,
  'digital-dubai': DIGITAL_DUBAI_SPEC,
  tamm: TAMM_SPEC,
  sahel: SAHEL_SPEC,
  metrash2: METRASH2_SPEC,
  hukoomi: HUKOOMI_SPEC,
  tasdeed: TASDEED_SPEC,

  // Government Country Fallbacks
  'gov_sa': GOV_SA_SPEC,
  'gov_ae': GOV_AE_SPEC,
  'gov_kw': GOV_KW_SPEC,
  'gov_qa': GOV_QA_SPEC,
  'gov_bh': GOV_BH_SPEC,
  'gov_om': GOV_OM_SPEC,

  // Payment Gateways
  sadad: SADAD_SPEC,
  knet: KNET_SPEC,
  benefit: BENEFIT_SPEC,
  dirham: DIRHAM_SPEC,
  jaywan: JAYWAN_SPEC,
  maal: MAAL_SPEC,
  dubaipay: DUBAIPAY_SPEC,
  fawri: FAWRI_SPEC,
  omannet: OMANNET_SPEC,
  mada: MADA_SPEC,

  // Banks
  alrajhi: ALRAJHI_SPEC,
  snb: SNB_SPEC,
  'stc-pay': STC_PAY_SPEC,
  urpay: URPAY_SPEC,
  enbd: ENBD_SPEC,
  fab: FAB_SPEC,
  nbk: NBK_SPEC,
  qnb: QNB_SPEC,
  'bank-muscat': BANK_MUSCAT_SPEC,
  nbb: NBB_SPEC,
};

// ============================================
// HELPER FUNCTIONS
// ============================================

/**
 * Get visual spec for an entity by its key
 */
export const getEntityVisualSpec = (entityKey: string): EntityVisualSpec | null => {
  const key = entityKey.toLowerCase().replace(/[_\s-]+/g, '-');
  
  // Direct match
  if (ENTITY_VISUAL_REGISTRY[key]) {
    return ENTITY_VISUAL_REGISTRY[key];
  }
  
  // Try with bank_ prefix
  if (key.startsWith('bank_')) {
    const bankKey = key.replace('bank_', '');
    if (ENTITY_VISUAL_REGISTRY[bankKey]) {
      return ENTITY_VISUAL_REGISTRY[bankKey];
    }
  }
  
  // Partial match
  for (const [registryKey, spec] of Object.entries(ENTITY_VISUAL_REGISTRY)) {
    if (key.includes(registryKey) || registryKey.includes(key)) {
      return spec;
    }
  }
  
  return null;
};

/**
 * Get all entities by category
 */
export const getEntitiesByCategory = (category: EntityVisualSpec['category']): EntityVisualSpec[] => {
  return Object.values(ENTITY_VISUAL_REGISTRY).filter(e => e.category === category);
};

/**
 * Get all entities by country
 */
export const getEntitiesByCountry = (countryCode: string): EntityVisualSpec[] => {
  return Object.values(ENTITY_VISUAL_REGISTRY).filter(e => e.countryCode === countryCode);
};

/**
 * Convert spec to CSS custom properties
 */
export const specToCSSVariables = (spec: EntityVisualSpec): Record<string, string> => {
  return {
    // Brand Colors
    '--brand-primary': spec.colors.primary,
    '--brand-secondary': spec.colors.secondary,
    '--brand-accent': spec.colors.accent,
    '--brand-background': spec.colors.background,
    '--brand-surface': spec.colors.surface,
    '--brand-text': spec.colors.text,
    '--brand-text-light': spec.colors.textLight,
    '--brand-text-on-primary': spec.colors.textOnPrimary,
    '--brand-border': spec.colors.border,
    
    // Input Colors
    '--brand-input-bg': spec.colors.inputBg,
    '--brand-input-border': spec.colors.inputBorder,
    
    // Button Colors
    '--brand-button': spec.colors.button,
    '--brand-button-hover': spec.colors.buttonHover,
    '--brand-button-text': spec.colors.buttonText,
    
    // Typography
    '--brand-font': spec.typography.fontFamily,
    '--brand-font-ar': spec.typography.fontFamilyAr,
    '--brand-heading-weight': spec.typography.headingWeight,
    '--brand-body-weight': spec.typography.bodyWeight,
    '--brand-font-size-base': spec.typography.fontSizeBase,
    '--brand-font-size-heading': spec.typography.fontSizeHeading,
    
    // Dimensions
    '--brand-container-max-width': spec.dimensions.containerMaxWidth,
    '--brand-border-radius': spec.dimensions.borderRadius,
    '--brand-button-height': spec.dimensions.buttonHeight,
    '--brand-input-height': spec.dimensions.inputHeight,
    '--brand-input-padding-x': spec.dimensions.inputPaddingX,
    '--brand-input-font-size': spec.dimensions.inputFontSize,
    '--brand-card-padding': spec.dimensions.cardPadding,
    '--brand-header-height': spec.dimensions.headerHeight,
    '--brand-logo-width': spec.dimensions.logoWidth,
    '--brand-logo-height': spec.dimensions.logoHeight,
    
    // Shadows
    '--brand-shadow-card': spec.shadows.card,
    '--brand-shadow-button': spec.shadows.button,
    '--brand-shadow-input': spec.shadows.input,
    '--brand-shadow-header': spec.shadows.header,
    '--brand-shadow-modal': spec.shadows.modal,
    
    // UI Config
    '--brand-button-shape': spec.uiComponents.buttonStyle === 'rounded' ? '12px' : spec.uiComponents.buttonStyle === 'pill' ? '9999px' : '0px',
    '--brand-input-style': spec.uiComponents.inputStyle,
    '--brand-has-gradient': spec.uiComponents.hasGradient ? '1' : '0',
    '--brand-gradient-direction': spec.uiComponents.gradientDirection,
    
    // Entity metadata
    '--brand-entity-id': spec.entityId,
    '--brand-entity-category': spec.category,
    '--brand-entity-country': spec.countryCode,
  };
};

export default ENTITY_VISUAL_REGISTRY;
